apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  DB_USERNAME: dXNlcm5hbWU=
  DB_PASSWORD: cGFzc3dvcmQ=

---

apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
# data:
#   POSTGRES_DB: $POSTGRES_DB
#   POSTGRES_USER: $POSTGRES_USER
#   POSTGRES_PASSWORD: $POSTGRES_PASSWORD



