apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
data:
  POSTGRES_HOST : postgres
  POSTGRES_DB : noteflow
  POSTGRES_USER : user
  POSTGRES_PASSWORD : '112a'
  POSTGRES_PORT : '5432'

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-configmap
data:
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: 112a
  MONGO_INITDB_DATABASE: noteflow

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-express-configmap
data:
  ME_CONFIG_MONGODB_URL: 'mongodb://$MONGO_INITDB_ROOT_USERNAME:$MONGO_INITDB_ROOT_PASSWORD@mongo:$MONGO_PORT/'

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
data:
  VITE_NOTEFLOW_BACKEND: ${NOTEFLOW_BACKEND}
  VITE_NOTEFLOW_PORT: '${BACKEND_EXPOSE_PORT}'
  VITE_DEV: '${VITE_DEV}'
  FRONTEND_EXPOSE_PORT: '${FRONTEND_EXPOSE_PORT}'


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
data:
    MONGO_HOST: $MONGO_HOST
    MONGO_DB: $MONGO_DB
    MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
    MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    MONGO_NOTEFLOW_USERNAME: $MONGO_NOTEFLOW_USERNAME
    MONGO_NOTEFLOW_PASSWORD: $MONGO_NOTEFLOW_PASSWORD
    MONGO_PORT: '$MONGO_PORT'
    PHOTO_FS: $PHOTO_FS

    POSTGRES_HOST: $POSTGRES_HOST
    POSTGRES_DB: $POSTGRES_DB
    POSTGRES_USER: $POSTGRES_USER
    POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    POSTGRES_PORT: '$POSTGRES_PORT'

    REDIS_HOST: $REDIS_HOST
    REDIS_PORT: '$REDIS_PORT'
    REDIS_SESSION_HOST: $REDIS_SESSION_HOST
    REDIS_SESSION_PORT: '$REDIS_SESSION_PORT'
    REDIS_ACCOUNT: $REDIS_ACCOUNT
    REDIS_PASSWORD: $REDIS_PASSWORD

    S3_BUCKET_REGION: $S3_BUCKET_REGION

    EMAIL_HOST: $EMAIL_HOST
    EMAIL_USER: $EMAIL_USER
    EMAIL_PASSWORD: $EMAIL_PASSWORD
    REFRESH_TOKEN: $REFRESH_TOKEN
    CLIENT_SECRET: $CLIENT_SECRET
    CLIENT_ID: $CLIENT_ID
    INIT_CMD1: "mongosh -u ${MONGO_INITDB_ROOT_USERNAME} -p ${MONGO_INITDB_ROOT_PASSWORD} --host ${MONGO_HOST} --port ${MONGO_PORT} -e ${MONGO_BOOTSTRAP_CMD}"


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: migrate-configmap
data:
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_PORT: '$POSTGRES_PORT'