apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  DB_USERNAME: dXNlcm5hbWU=
  DB_PASSWORD: cGFzc3dvcmQ=

---

apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
# data:
#   POSTGRES_DB: noteflow
#   POSTGRES_USER: user
#   POSTGRES_PASSWORD: 112a

---

apiVersion: v1
kind: Secret
metadata:
  name: mongo-express-secret
type: Opaque
data:
  ME_CONFIG_BASICAUTH_USERNAME: jounglab112a
  ME_CONFIG_BASICAUTH_PASSWORD: 112a
  ME_CONFIG_MONGODB_ADMINUSERNAME: root
  ME_CONFIG_MONGODB_ADMINPASSWORD: 112a

---

