## postgres

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nf-postgres-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast
  gcePersistentDisk:
    pdName: my-disk
    fsType: ext4

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nf-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: fast

## mongodb

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nf-mongo-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast
  gcePersistentDisk:
    pdName: my-disk
    fsType: ext4

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nf-mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: fast

## backend

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nf-backend-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast
  gcePersistentDisk:
    pdName: my-disk
    fsType: ext4

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nf-backend-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: fast
